name: helloworld
on: push
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Get the repos files by checkout
      uses: actions/checkout@master
    - name: Send the Docker Image to Githubs Package Registry
      uses: machine-learning-apps/gpr-docker-publish@master
      with:
        cache: true
#        branch_tag: true
        IMAGE_NAME: 'helloworld'
        TAG: 'latest'
        DOCKERFILE_PATH: 'helloworld/Dockerfile'
        BUILD_CONTEXT: './helloworld'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} ## this is the secret from your account

# https://help.github.com/en/actions/reference/contexts-and-expression-syntax-for-github-actions